apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: keycloak
spec:
  hostname: "keycloak1.cp.k736.net"
  prefix: /
  service: keycloak.ambassador:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: keycloak-host
spec:
  hostname: "keycloak1.cp.k736.net"
  acmeProvider:
    email: cpetterson@datawire.io

