apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  hostname: "*"
  prefix: /backend/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quotefrontend
spec:
  hostname: "demo1.cp.k736.net"
  prefix: /
  service: quotefrontend
  cors:
    origins:
    - "http://demo1.cp.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-api
spec:
  hostname: "demo1.cp.k736.net"
  prefix: "/quote/"
  service: quote.ambassador:80



